### ISSUE TITLE
Slow tab-switching in large sketch collection reports

### ISSUE THREAD

**Issue by avmey** [mcclintock-lab/bermuda-reports#9]
Tabbing between top-level report clients becomes increasingly slow. 

- Occurs only when the data begins to be received by the report
- When you switch tabs, it's regenerating all client cards (even now-hidden ones)
- flattenBySketchAllClass() seems to be the main offender

Possible solutions:
- memoizing flattenBySketchAllClass() so results can be cached
- ensure only visible cards are generating

**Comment by avmey** [comment]
Reopening this issue specifically regarding slowness in map layer toggles in the reports.

**Comment by twelch** [comment]
Options going forward:
* make flattenBySketchClass more efficient
* make flattenBySketchClass async and show a load indicator in the meantime
* use third-party memoize function to cache results of flattenBySketchClass

**Comment by twelch** [comment]
useEffect for lazy loading of table?  useCallback?

**Comment by twelch** [comment]
See new upstream ticket related to remounting behavior - https://github.com/seasketch/geoprocessing/issues/176

**Comment by avmey** [comment]
Solution: Created a memo version of `flattenBySketchAllClass()`, the function which took the longest time to re-render. The new function is called `flattenBySketchAllClassMemo()`, and is locally stored in functions/util/helpers.ts. It requires importing memoize from "micro-memoize" and { deepEqual } from "fast-equals".

```
/**
 * Memoized version of flattenBySketchAllClass
 * Flattens group class metrics, one for each group and sketch.
 * Each object includes the percValue for each class, and the total percValue with classes combined
 * groupId, sketchId, class1, class2, ...
 * @param groupMetrics - group metric data
 * @param totalValue - total value with classes combined
 * @param classes - class config
 */
export const flattenBySketchAllClassMemo = memoize(flattenBySketchAllClass, {
  maxSize: 20, // Able to store 20 keys in cache (1 key = 1 sketch table)
  isEqual: deepEqual, // Necessary to compare deep objects being flattened
});
```

---

To debug caching, particularly on layer-toggling, particularly for Bermuda:

1. Add logging statements to memoized function with `onCacheAdd()` and `onCacheHit()` functions
2. `cd node_modules/@seasketch/geoprocessing`
3. Update `package.json` with `"webpack": "4.46.0", "webpack-bundle-analyzer": "4.4.2", "webpack-cli": "4.10.0", "webpack-dev-server": "4.13.2"`
4. Run `PROJECT_PATH=/Users/avmey/bermuda-reports DEBUG='express:*' npx webpack serve --config scripts/build/webpack.clients.config.js --mode="development" --client-logging verbose --progress --watch-files "/Users/avmey/bermuda-reports/src"` with /Users/avmey/bermuda-reports replaced according to your directory location
5. Navigate to `localhost:8080` and add service to url to point it to the publish gp prod, example: http://localhost:8080/?service=https://gle8for8df.execute-api.us-east-1.amazonaws.com/prod/
6. Open dev tools and post message. Example message:
`window.postMessage({
    "type": "SeaSketchReportingMessageEventType",
    "client": "AllReports",
    "language": "pt",
    "geometryUri": "https://legacy.seasketch.org/geojson/646b8399a2a6ff4133be30ce",
    "sketchProperties": {
        "id": "646b8399a2a6ff4133be30ce",
        "name": "Test Example Project",
        "createdAt": "2021-04-20T20:28:03.607Z",
        "updatedAt": "2021-04-20T20:28:03.607Z",
        "sketchClassId": "615b65a2aac8c8285d50d9f3",
        "isCollection": true,
        "userAttributes": [],
        "visibleLayers": []
    }
})`
